apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ep3
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Root12345
  DB_USERNAME: root
  DB_PASSWORD: Root12345
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: ep3
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS ventas_db;
    CREATE DATABASE IF NOT EXISTS despachos_db;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ep3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: mysql-storage
          emptyDir: {}
        - name: mysql-initdb
          configMap:
            name: mysql-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ep3
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306